name: earth-analytics-python
channels:
  - conda-forge
  - defaults
dependencies:
  - access=1.1.3=pyhd8ed1ab_0
  - affine=2.3.0=py_0
  - alembic=1.5.6=pyhd8ed1ab_0
  - ansiwrap=0.8.4=py_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=20.1.0=py38h294d835_2
  - async_generator=1.10=py_0
  - atomicwrites=1.4.0=pyh9f0ad1d_0
  - attrs=20.3.0=pyhd3deb0d_0
  - autopep8=1.5.4=pyh9f0ad1d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - beautifulsoup4=4.9.3=pyhb0f4dca_0
  - black=20.8b1=py_1
  - bleach=3.3.0=pyh44b312d_0
  - blinker=1.4=py_1
  - blosc=1.21.0=h0e60522_0
  - boost-cpp=1.74.0=h54f0996_2
  - branca=0.4.2=pyhd8ed1ab_0
  - brotli=1.0.9=h0e60522_4
  - bs4=4.9.3=0
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2021.4.13=haa95532_1
  - cairo=1.16.0=hba8bd2f_1007
  - cartopy=0.18.0=py38h7c06ecb_13
  - certifi=2020.12.5=py38haa95532_0
  - cffi=1.14.5=py38hd8c33c5_0
  - cfitsio=3.470=h0af3d06_7
  - cftime=1.4.1=py38h347fdf6_0
  - chardet=4.0.0=py38haa244fe_1
  - charls=2.2.0=h39d44d4_0
  - chroma-py=0.1.0.dev1=py_0
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.1=pyhd8ed1ab_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - colour=0.1.5=py_0
  - contextily=1.0.1=py_0
  - coverage=5.5=py38h294d835_0
  - cryptography=3.4.5=py38hd7da0ea_1
  - curl=7.75.0=hf1763fc_0
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py38h294d835_3
  - dask-core=2021.3.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_1
  - decorator=4.4.2=py_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - descartes=1.1.0=py_4
  - earthpy=0.9.2=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - esda=2.3.6=pyhd8ed1ab_0
  - expat=2.2.10=h39d44d4_0
  - fiona=1.8.18=py38h91b197a_1
  - folium=0.11.0=py_0
  - fontconfig=2.13.1=h1989441_1004
  - freetype=2.10.4=h546665d_1
  - freexl=1.0.5=hd288d7e_1002
  - future=0.18.2=py38haa244fe_3
  - fuzzywuzzy=0.18.0=pyhd8ed1ab_0
  - gdal=3.2.1=py38hb9e1232_7
  - geocoder=1.38.1=py_1
  - geographiclib=1.50=py_0
  - geojson=2.5.0=py_0
  - geopandas=0.9.0=pyhd8ed1ab_0
  - geopy=2.0.0=pyh9f0ad1d_0
  - geos=3.9.1=h39d44d4_2
  - geotiff=1.6.0=hee96dd5_4
  - gettext=0.19.8.1=h1a89ca6_1005
  - giddy=2.3.3=py_0
  - giflib=5.2.1=h8d14728_2
  - hdf4=4.2.13=h0e5069d_1004
  - hdf5=1.10.6=nompi_h5268f04_1114
  - hydrofunctions=0.1.7=py_1
  - icu=68.1=h0e60522_0
  - idna=2.10=pyh9f0ad1d_0
  - imagecodecs=2021.1.28=py38hb9201fa_0
  - imageio=2.9.0=py_0
  - importlib-metadata=3.7.2=py38haa244fe_0
  - inequality=1.0.0=py_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - intel-openmp=2020.3=h57928b3_311
  - ipykernel=5.5.0=py38hc5df569_1
  - ipython=7.19.0=py38hc5df569_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - jedi=0.18.0=py38haa244fe_2
  - jinja2=2.11.3=pyh44b312d_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h8ffe710_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter=1.0.0=py38haa244fe_6
  - jupyter_client=6.1.11=pyhd8ed1ab_1
  - jupyter_console=6.2.0=py_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=py38h32f6830_1
  - jupyter_core=4.7.1=py38haa244fe_0
  - jupyter_highlight_selected_word=0.2.0=py38haa244fe_1002
  - jupyter_latex_envs=1.4.6=pyhd8ed1ab_1002
  - jupyter_nbextensions_configurator=0.4.1=py38haa244fe_2
  - jupyterlab=2.2.9=py_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=1.2.0=py_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - jxrlib=1.1=h8ffe710_2
  - kealib=1.4.14=h96bfa42_2
  - kiwisolver=1.3.1=py38hbd9d945_0
  - krb5=1.17.2=hbae68bd_0
  - lcms2=2.12=h2a16943_0
  - lerc=2.2.1=h0e60522_0
  - libaec=1.0.4=h39d44d4_1
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libclang=11.1.0=default_h5c34c98_0
  - libcurl=7.75.0=hf1763fc_0
  - libdeflate=1.7=h8ffe710_5
  - libffi=3.3=h0e60522_2
  - libgdal=3.2.1=hca2c63a_7
  - libglib=2.66.7=h1e62bf3_1
  - libiconv=1.16=he774522_0
  - libkml=1.3.0=h02ac0ef_1012
  - liblapack=3.9.0=8_mkl
  - libnetcdf=4.7.4=nompi_h3a9aa94_107
  - libpng=1.6.37=h1d00b33_2
  - libpq=13.1=h4f54205_2
  - libpysal=4.4.0=pyhd8ed1ab_0
  - librttopo=1.1.0=hb340de5_6
  - libsodium=1.0.18=h8d14728_1
  - libspatialindex=1.9.3=h39d44d4_3
  - libspatialite=5.0.1=h987baeb_3
  - libssh2=1.9.0=h680486a_6
  - libtiff=4.2.0=hc10be44_0
  - libwebp-base=1.2.0=h8ffe710_0
  - libxml2=2.9.10=hf5bbc77_3
  - libxslt=1.1.33=h65864e5_2
  - libzopfli=1.0.3=h0e60522_0
  - llvmlite=0.35.0=py38h57a6900_1
  - lxml=4.6.2=py38h292cb97_1
  - lz4-c=1.9.3=h8ffe710_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mako=1.1.4=pyh44b312d_0
  - mapboxgl=0.10.2=py_1
  - mapclassify=2.4.2=pyhd8ed1ab_0
  - markupsafe=1.1.1=py38h294d835_3
  - matplotcheck=0.1.2=py_1
  - matplotlib=3.3.2=py38haa244fe_1
  - matplotlib-base=3.3.2=py38h6584adb_1
  - mercantile=1.1.6=pyh9f0ad1d_0
  - mgwr=2.1.2=py_0
  - mistune=0.8.4=py38h294d835_1003
  - mkl=2020.4=hb70f87d_311
  - mock=4.0.3=py38haa244fe_1
  - more-itertools=8.7.0=pyhd8ed1ab_0
  - mpmath=1.2.1=pyhd8ed1ab_0
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - mypy_extensions=0.4.3=py38haa244fe_3
  - nbclean=0.3.2=pyh5ca1d4c_0
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py38haa244fe_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - nbgrader=0.6.1=py38h32f6830_0
  - nc-time-axis=1.2.0=py_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - netcdf4=1.5.4=nompi_py38h87f19a6_103
  - networkx=2.5=py_0
  - nltk=3.4.4=py_0
  - nose=1.3.7=py_1006
  - notebook=6.1.5=py38haa244fe_0
  - numba=0.52.0=py38h4c96930_0
  - numexpr=2.7.3=py38h4c96930_0
  - numpy=1.19.4=py38h0cc643e_1
  - oauthlib=3.0.1=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h48faf41_0
  - openssl=1.1.1k=h2bbff1b_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.3=py38h4c96930_0
  - pandoc=2.12=h8ffe710_0
  - pandocfilters=1.4.2=py_1
  - papermill=2.2.2=pyhd8ed1ab_0
  - parso=0.8.1=pyhd8ed1ab_0
  - pathspec=0.8.1=pyhd3deb0d_0
  - patsy=0.5.1=py_0
  - pcre=8.44=ha925a31_0
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.2=py38h9273828_0
  - pip=20.2.4=py_0
  - pixman=0.40.0=h8ffe710_0
  - pluggy=0.13.1=py38haa244fe_4
  - pointpats=2.2.0=py_0
  - pooch=1.3.0=pyhd8ed1ab_0
  - poppler=0.89.0=h3772339_5
  - poppler-data=0.4.10=0
  - postgresql=13.1=h0f1a9bc_2
  - proj=7.2.0=h1cfcee9_2
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.16=pyha770c72_0
  - prompt_toolkit=3.0.16=hd8ed1ab_0
  - py=1.10.0=pyhd3deb0d_0
  - pycodestyle=2.6.0=pyh9f0ad1d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygeos=0.9=py38hb69e06a_4
  - pygments=2.8.1=pyhd8ed1ab_0
  - pyjwt=2.0.1=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=3.0.1=py38h0ae89ba_0
  - pyqt=5.12.3=py38h6538335_1
  - pyrsistent=0.17.3=py38h294d835_2
  - pysal=2.3.0=py_0
  - pyshp=2.1.3=pyh44b312d_0
  - pysocks=1.7.1=py38haa244fe_3
  - pytables=3.6.1=py38h153c448_3
  - pytest=6.2.2=py38haa244fe_0
  - pytest-cov=2.11.1=pyh44b312d_0
  - python=3.8.6=h60c2a47_0_cpython
  - python-dateutil=2.8.0=py_0
  - python-editor=1.0.4=py_0
  - python-levenshtein=0.12.2=py38h294d835_0
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pywavelets=1.1.1=py38h347fdf6_3
  - pywin32=300=py38h294d835_0
  - pywinpty=0.5.7=py38h32f6830_1
  - pyyaml=5.4.1=py38h294d835_0
  - pyzmq=22.0.3=py38h09162b1_1
  - qt=5.12.9=h5909a2a_4
  - qtconsole=5.0.2=pyhd8ed1ab_0
  - qtpy=1.9.0=py_0
  - quantecon=0.4.8=py38_0
  - rasterio=1.2.1=py38h393d562_2
  - rasterstats=0.14.0=py_0
  - ratelim=0.1.6=py_2
  - regex=2020.11.13=py38h294d835_1
  - regionmask=0.6.1=py_1
  - requests=2.25.1=pyhd3deb0d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rioxarray=0.3.1=pyhd8ed1ab_0
  - rtree=0.9.7=py38h8b54edf_1
  - scikit-image=0.18.1=py38h4c96930_0
  - scikit-learn=0.24.1=py38ha09990b_0
  - scipy=1.5.3=py38h5f893b4_0
  - seaborn=0.11.0=h57928b3_1
  - seaborn-base=0.11.0=py_0
  - segregation=1.5.0=pyhd8ed1ab_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py38haa244fe_3
  - shapely=1.7.1=py38h2426642_4
  - simplejson=3.17.2=py38h294d835_2
  - six=1.15.0=pyh9f0ad1d_0
  - snappy=1.1.8=ha925a31_3
  - snuggs=1.4.7=py_0
  - soupsieve=2.0.1=py_1
  - spaghetti=1.5.6=pyhd8ed1ab_0
  - spglm=1.0.8=py_0
  - spint=1.0.7=pyhd8ed1ab_0
  - splot=1.1.3=pyhd8ed1ab_1
  - spreg=1.2.2=pyhd8ed1ab_0
  - spvcm=0.3.0=py_0
  - sqlalchemy=1.3.23=py38h294d835_0
  - sqlite=3.34.0=h8ffe710_0
  - statsmodels=0.12.2=py38h347fdf6_0
  - sympy=1.7.1=py38haa244fe_1
  - tenacity=7.0.0=pyhd8ed1ab_0
  - terminado=0.9.2=py38haa244fe_0
  - testpath=0.4.4=py_0
  - textblob=0.15.3=py_0
  - textwrap3=0.9.2=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tifffile=2021.3.5=pyhd8ed1ab_0
  - tiledb=2.2.4=hddc2a84_1
  - tk=8.6.10=h8ffe710_1
  - tobler=0.6.0=pyhd8ed1ab_0
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.11.1=py_0
  - tornado=6.1=py38h294d835_1
  - tqdm=4.51.0=pyh9f0ad1d_0
  - traitlets=5.0.5=py_0
  - tweepy=3.9.0=pyh9f0ad1d_0
  - typed-ast=1.4.2=py38h294d835_0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.24.3=py_1
  - vc=14.2=hb210afc_4
  - vs2015_runtime=14.28.29325=h5e1d092_4
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3deb0d_0
  - widgetsnbextension=3.5.1=py38haa244fe_4
  - win_inet_pton=1.1.0=py38haa244fe_2
  - wincertstore=0.2=py38haa244fe_1006
  - winpty=0.4.3=4
  - xarray=0.16.1=py_0
  - xerces-c=3.2.3=h0e60522_2
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.4=h0e60522_0
  - zfp=0.5.5=h0e60522_4
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h62dcd97_1010
  - zstd=1.4.9=h6255e5f_0
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: C:\Users\Michael\miniconda3\envs\earth-analytics-python
